package Vista;

public class UIADMININFORMACION extends javax.swing.JFrame {

    /**
     * Creates new form UIADMININFORMACION
     */
    public UIADMININFORMACION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBlanco = new javax.swing.JPanel();
        Bienvenido3 = new javax.swing.JLabel();
        BuscarField = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        CrearUsuarioBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CrearUsuarioBTN1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaInfo = new javax.swing.JTextArea();
        panelAzul = new javax.swing.JPanel();
        Bienvenido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        PanelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenido3.setBackground(new java.awt.Color(0, 0, 0));
        Bienvenido3.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        Bienvenido3.setText("Buscar Tutoriales");
        PanelBlanco.add(Bienvenido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        PanelBlanco.add(BuscarField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, 30));

        searchbtn.setBackground(new java.awt.Color(185, 189, 193));
        searchbtn.setForeground(new java.awt.Color(185, 189, 193));
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DashBoard Usuario/search 1.png"))); // NOI18N
        searchbtn.setBorder(null);
        searchbtn.setBorderPainted(false);
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        PanelBlanco.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 40, 30));

        CrearUsuarioBTN.setBackground(new java.awt.Color(59, 159, 255));
        CrearUsuarioBTN.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        CrearUsuarioBTN.setForeground(new java.awt.Color(255, 255, 255));
        CrearUsuarioBTN.setText("Actualizar Tutorial");
        CrearUsuarioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBTNActionPerformed(evt);
            }
        });
        PanelBlanco.add(CrearUsuarioBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 170, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tutorial"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PanelBlanco.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 570, 110));

        CrearUsuarioBTN1.setBackground(new java.awt.Color(59, 159, 255));
        CrearUsuarioBTN1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        CrearUsuarioBTN1.setForeground(new java.awt.Color(255, 255, 255));
        CrearUsuarioBTN1.setText("Eliminar Tutorial");
        CrearUsuarioBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBTN1ActionPerformed(evt);
            }
        });
        PanelBlanco.add(CrearUsuarioBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 170, 40));

        textAreaInfo.setColumns(20);
        textAreaInfo.setRows(5);
        jScrollPane2.setViewportView(textAreaInfo);

        PanelBlanco.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 560, 240));

        getContentPane().add(PanelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 620, 640));

        panelAzul.setBackground(new java.awt.Color(35, 69, 169));

        Bienvenido.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenido.setText("Administracion de informacion");

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Bienvenido)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Bienvenido)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearUsuarioBTNActionPerformed

    private void CrearUsuarioBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearUsuarioBTN1ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIADMININFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIADMININFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIADMININFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIADMININFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIADMININFORMACION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Bienvenido3;
    private javax.swing.JTextField BuscarField;
    private javax.swing.JButton CrearUsuarioBTN;
    private javax.swing.JButton CrearUsuarioBTN1;
    private javax.swing.JPanel PanelBlanco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextArea textAreaInfo;
    // End of variables declaration//GEN-END:variables
}
