package Vista;

public class UIADMININFORMACION extends javax.swing.JFrame {

    /**
     * Creates new form adminInfoVista
     */
    public UIADMININFORMACION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelAzul = new javax.swing.JPanel();
        Bienvenido = new javax.swing.JLabel();
        Bienvenido3 = new javax.swing.JLabel();
        buscarField = new javax.swing.JTextField();
        buscarBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInfo = new javax.swing.JTable();
        eliminarTutoBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoField = new javax.swing.JTextArea();
        updateBTN = new javax.swing.JButton();
        todosBTN = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JLabel();
        crearBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAzul.setBackground(new java.awt.Color(35, 69, 169));

        Bienvenido.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenido.setText("Administracion de informacion");

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Bienvenido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Bienvenido)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Bienvenido3.setBackground(new java.awt.Color(0, 0, 0));
        Bienvenido3.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        Bienvenido3.setText("Buscar Tutoriales");

        buscarBTN.setBackground(new java.awt.Color(59, 159, 255));
        buscarBTN.setForeground(new java.awt.Color(185, 189, 193));
        buscarBTN.setText("BUSCAR");
        buscarBTN.setBorder(null);
        buscarBTN.setBorderPainted(false);
        buscarBTN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarBTNActionPerformed(evt);
            }
        });

        tablaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "ID", "Nombre", "Fecha"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tablaInfo.getTableHeader().setResizingAllowed(false);
        tablaInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaInfo);

        eliminarTutoBTN.setBackground(new java.awt.Color(59, 159, 255));
        eliminarTutoBTN.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        eliminarTutoBTN.setForeground(new java.awt.Color(255, 255, 255));
        eliminarTutoBTN.setText("Eliminar Tutorial");
        eliminarTutoBTN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminarTutoBTNActionPerformed(evt);
            }
        });

        infoField.setColumns(20);
        infoField.setRows(5);
        jScrollPane2.setViewportView(infoField);

        updateBTN.setBackground(new java.awt.Color(59, 159, 255));
        updateBTN.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        updateBTN.setForeground(new java.awt.Color(255, 255, 255));
        updateBTN.setText("Actualizar");
        updateBTN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateBTNActionPerformed(evt);
            }
        });

        todosBTN.setBackground(new java.awt.Color(59, 159, 255));
        todosBTN.setForeground(new java.awt.Color(185, 189, 193));
        todosBTN.setText("TODOS");
        todosBTN.setToolTipText("");
        todosBTN.setBorder(null);
        todosBTN.setBorderPainted(false);
        todosBTN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                todosBTNActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        Nombre.setText("Id");

        nombreField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreFieldActionPerformed(evt);
            }
        });

        Nombre1.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        Nombre1.setText("Nombre ");

        IDField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                IDFieldActionPerformed(evt);
            }
        });

        Nombre2.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N

        crearBTN.setBackground(new java.awt.Color(59, 159, 255));
        crearBTN.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        crearBTN.setForeground(new java.awt.Color(255, 255, 255));
        crearBTN.setText("Crear");
        crearBTN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                crearBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(todosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Bienvenido3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eliminarTutoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(crearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Nombre1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Nombre)
                                    .addGap(12, 12, 12)
                                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(188, 188, 188))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Nombre2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bienvenido3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarTutoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre1)
                                    .addComponent(Nombre)
                                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Nombre2))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBTNActionPerformed

    private void eliminarTutoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTutoBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarTutoBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBTNActionPerformed

    private void todosBTNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_todosBTNActionPerformed
    {//GEN-HEADEREND:event_todosBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todosBTNActionPerformed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreFieldActionPerformed
    {//GEN-HEADEREND:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_IDFieldActionPerformed
    {//GEN-HEADEREND:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    private void crearBTNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_crearBTNActionPerformed
    {//GEN-HEADEREND:event_crearBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIADMININFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIADMININFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIADMININFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIADMININFORMACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIADMININFORMACION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Bienvenido1;
    private javax.swing.JLabel Bienvenido2;
    private javax.swing.JLabel Bienvenido3;
    private javax.swing.JLabel Bienvenido4;
    public javax.swing.JTextField IDField;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    public javax.swing.JButton buscarBTN;
    public javax.swing.JTextField buscarField;
    public javax.swing.JButton crearBTN;
    public javax.swing.JButton eliminarTutoBTN;
    public javax.swing.JTextArea infoField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField nombreField;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelAzul1;
    private javax.swing.JPanel panelAzul2;
    private javax.swing.JPanel panelAzul3;
    public javax.swing.JTable tablaInfo;
    public javax.swing.JButton todosBTN;
    public javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
