package Vista;

import java.awt.Color;
import java.util.HashSet;

public class UILOGIN extends javax.swing.JFrame {

    /**
     * Creates new form UILOGIN
     */
    
    int xMouse, yMouse;
    public UILOGIN() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        Password = new javax.swing.JPasswordField();
        passwordlines = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jRECTANGLE1 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        jLOGINTEXT = new javax.swing.JLabel();
        jLineas = new javax.swing.JLabel();
        jManchas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        setResizable(false);

        jFondo.setBackground(new java.awt.Color(31, 65, 169));
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password.setBackground(new java.awt.Color(31, 65, 169));
        Password.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(165, 165, 165));
        Password.setText("************");
        Password.setToolTipText("PassWord");
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jFondo.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 340, 30));

        passwordlines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DashBoard Usuario/Rectangle 1.png"))); // NOI18N
        jFondo.add(passwordlines, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 370, 50));

        Username.setBackground(new java.awt.Color(31, 65, 169));
        Username.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(165, 165, 165));
        Username.setText("Username");
        Username.setBorder(null);
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsernameMousePressed(evt);
            }
        });
        jFondo.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 340, 40));

        jRECTANGLE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DashBoard Usuario/Rectangle 1.png"))); // NOI18N
        jFondo.add(jRECTANGLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 370, 60));

        loginbtn.setBackground(new java.awt.Color(31, 65, 169));
        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DashBoard Usuario/LoginButton2.png"))); // NOI18N
        loginbtn.setBorder(null);
        loginbtn.setBorderPainted(false);
        loginbtn.setContentAreaFilled(false);
        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn.setFocusPainted(false);
        loginbtn.setRequestFocusEnabled(false);
        loginbtn.setRolloverEnabled(false);
        loginbtn.setVerifyInputWhenFocusTarget(false);
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jFondo.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 370, 60));

        jLOGINTEXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DashBoard Usuario/Texts.png"))); // NOI18N
        jLOGINTEXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jFondo.add(jLOGINTEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 400, 90));

        jLineas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DashBoard Usuario/AppBody.png"))); // NOI18N
        jLineas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jFondo.add(jLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 450, 450));

        jManchas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DashBoard Usuario/BG.png"))); // NOI18N
        jManchas.setToolTipText("");
        jManchas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jManchas.setFocusable(false);
        jManchas.setInheritsPopupMenu(false);
        jManchas.setRequestFocusEnabled(false);
        jManchas.setVerifyInputWhenFocusTarget(false);
        jFondo.add(jManchas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMousePressed
        // TODO add your handling code here:
        if(Username.getText().equals("Username")){
            Username.setText("");
            Username.setForeground(new Color (165,165,165)); 
        }
        
        if(String.valueOf(Password.getPassword()).isEmpty()){
            Password.setText("************");
            Password.setForeground(new Color (165,165,165));
        }  
            
    }//GEN-LAST:event_UsernameMousePressed

    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed
        if(String.valueOf(Password.getPassword()).equals("************")){
            Password.setText("");
            Password.setForeground(new Color (165,165,165));
        }
        if(Username.getText().isEmpty()){
             Username.setText("Username");
             Username.setForeground(new Color (165,165,165));
      
        }
    }//GEN-LAST:event_PasswordMousePressed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UILOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UILOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UILOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UILOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UILOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPasswordField Password;
    public javax.swing.JTextField Username;
    private javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLOGINTEXT;
    private javax.swing.JLabel jLineas;
    private javax.swing.JLabel jManchas;
    private javax.swing.JLabel jRECTANGLE1;
    public javax.swing.JButton loginbtn;
    private javax.swing.JLabel passwordlines;
    // End of variables declaration//GEN-END:variables
}
